Changed db destination to app directory

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -16,8 +16,8 @@ city_checksum=$(curl http://geolite.maxmind.com/download/geoip/database/GeoLite2
 country_checksum=$(curl http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.md5)
 echo "-----> Download complete. Verifying checksum..."
 
-city=$(cat ./geolite/city.mmdb.gz | md5)
-country=$(cat ./geolite/country.mmdb.gz | md5)
+city=$(cat ./geolite/city.mmdb.gz | md5sum)
+country=$(cat ./geolite/country.mmdb.gz | md5sum)
 echo $city_checksum
 echo $city
 echo $country_checksum
@@ -26,4 +26,8 @@ echo $country
 
 if ! [ $city == $city_checksum ]; then
   echo "-----> ERROR: city db checksums does not match"
+fi
+
+if ! [ $country == $country_checksum ]; then
+  echo "-----> ERROR: country db checksums does not match"
 fi
